bringing back indexer-processor
movementlabsxyz/movement pull request #262
Opened 2024-07-26 19:07 UTC by 0xPrimata

# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

Readding modifications made by @l-monninger 
https://github.com/movementlabsxyz/movement/pull/124

# Changelog

# Testing

# Outstanding issues

2024-07-26 19:09 UTC, l-monninger approved these changes

2024-07-26 19:09 UTC, l-monninger commented on scripts/cargo/choose
> +ln -sf Cargo.$1.toml Cargo.toml
This can be deleted.

2024-07-26 19:09 UTC, l-monninger commented on process-compose/suzuka-full-node/process-compose.yml
> +      # todo: this fails with gRPC Unimplemented error on the RawData.GetTransactions call
It would be nice to test the `indexer-processor` prior to proceeding. But, I think that's going to be difficult.

2024-07-26 19:10 UTC, l-monninger requested changes

2024-07-26 19:10 UTC, l-monninger commented on Cargo.toml
> +# indexer
I think you should update this to the latest rather than the commit on my branch.

2024-07-29 03:28 UTC, 0xPrimata commented
Notes on how things currently stand:
1. Despite changing the [processor type](https://github.com/movementlabsxyz/movement/blob/e04042abc801f504b161c123915a2ae6b1626e52/protocol-units/execution/opt-executor/src/executor/initialization.rs#L167), suzuka-indexer-processor runs default_processor every time. Have tried with a few different names. Is it possible that because indexer-processor is being pulled remotely, configuration is ignored?

Because Aptos informs us that [aptos-indexer-processor](https://aptos.dev/en/build/indexer/txn-stream/labs-hosted) SHOULD run a TSS and the [Indexer API](https://aptos.dev/en/build/indexer/api/self-hosted) is essentially configed by what @l-monninger provided, I went down the rabbit hole of checking if the API is actually provided or not.
2. Tested a few different endpoints to check if suzuka-indexer-processor would be serving the graphql api, none worked:
http://localhost:30734/graphql
http://localhost:30731/graphql
localhost:30730/graphql
localhost:30734/graphql
localhost:30731/graphql
localhost:30730/graphql
http://0.0.0.0:30734/graphql
http://0.0.0.0:30731/graphql
http://0.0.0.0:30730/graphql
http://0.0.0.0:30734/graphql
http://0.0.0.0:30731/graphql
http://0.0.0.0:30730/graphql
http://localhost:30734
http://localhost:30731
localhost:30730
localhost:30734
localhost:30731
localhost:30730
http://0.0.0.0:30734
http://0.0.0.0:30731
http://0.0.0.0:30730
http://0.0.0.0:30734
http://0.0.0.0:30731
http://0.0.0.0:30730
https://cloud.hasura.io/public/graphiql?endpoint=https://api.devnet.aptoslabs.com/v1/graphql custom endpoints are also not returning anything

3. `curl http://localhost:30734` (and curl localhost:30734?auth_token=notrealnotneeded too) gives us curl: `(1) Received HTTP/0.9 when not allowed` -> `curl: (56) Recv failure: Connection reset by peer.`

4. Going back to implementing the two next requirements: relational db and the API. Checking if the relational db is being served. I can see that we are not providing a Redis db. That should be the relational db, so I ended up here: https://github.com/aptos-labs/aptos-core/tree/f2a427f3f4c1b883c2a9588a1c39db515637de0d/ecosystem/indexer-grpc. Which matches, notes provided in [notion](https://www.notion.so/movementlabs/Indexing-Suzuka-e0bbaf50918a4ba0adada51e07038641). A bit unsure on how to proceed here, provided some notes.

5. Started configing services pointed out in our Notion file.

2024-07-29 08:55 UTC, l-monninger commented
@0xPrimata

> Tested a few different endpoints to check if suzuka-indexer-processor would be serving the graphql api, none worked:

The endpoints you are testing serve the gRPC full node data stream. The role of the indexer processor is to take that data and put it in a `postgres` database. You can then use Hasura with the schemes from the upstream to serve that database behind a GraphQL endpoint. 

On the otherhand, what's being served on `:30734` is the gRPC full node data stream service. You can see how to consume it by consulting the tests: https://github.com/movementlabsxyz/movement/blob/primata/implement-indexer-processor/networks/suzuka/suzuka-client/src/tests/indexer_stream.rs

> curl http://localhost:30734 (and curl localhost:30734?auth_token=notrealnotneeded too) gives us curl: (1) Received HTTP/0.9 when not allowed -> curl: (56) Recv failure: Connection reset by peer.

You cannot curl request a gRPC endpoint. For exploring, using `grpcurl` or `grpcui` (both included in the nix flake).

2024-08-05 12:29 UTC, closed without merging