Primata/314 weth eth amount type
movementlabsxyz/movement pull request #426
Opened 2024-08-22 00:48 UTC by 0xPrimata

# Summary
- **RFCs**: https://github.com/movementlabsxyz/movement/issues/405
- **Categories**: `protocol-units`

Adds bridge_transfers(bridgeTransferId) view function to move contracts

# Changelog

# Testing

Testing seems to cover but there is one issue with view functions behavior. it's altering the state and we would expect it to not do so.

# Outstanding issues

2024-08-26 13:18 UTC, andygolay commented
@0xPrimata any idea why the `[suzuka-full-node-local (ubuntu-22.04, x86_64, buildjet-16vcpu-ubuntu-2204)]` job is failing?

2024-08-26 13:21 UTC, andygolay requested changes
gm @0xPrimata 

- Any idea why the `[suzuka-full-node-local (ubuntu-22.04, x86_64, buildjet-16vcpu-ubuntu-2204)]` job is failing?

- Is `test_swap` the integration test for these changes?

2024-08-26 14:17 UTC, andygolay reviewed
Tests pass and make sense; pending CI passing, LGTM.

Will wait on CI resolution before approving.

2024-08-27 14:52 UTC, andygolay commented
> gm @0xPrimata
> 
> * Any idea why the `[suzuka-full-node-local (ubuntu-22.04, x86_64, buildjet-16vcpu-ubuntu-2204)]` job is failing?
> * Is `test_swap` the integration test for these changes?

The suzuka test passes now after re-running CI. 

LGTM

2024-08-27 15:04 UTC, 0xmovses approved these changes
This looks good! :shipit:

2024-08-27 15:04 UTC, 0xmovses commented on protocol-units/bridge/integration-tests/tests/eth_movement.rs
> +			Amount(AssetType::EthAndWeth((1, 1))),
👍

2024-08-27 15:04 UTC, 0xmovses commented on protocol-units/bridge/shared/src/bridge_contracts.rs
> +}
👍

2024-08-27 20:55 UTC, merged