Bridge Eth -> Mvt transfer e2e Test
movementlabsxyz/movement pull request #690
Opened 2024-10-11 21:39 UTC by musitdev

# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

# Changelog

# Testing

# Outstanding issues

Still an issue with LockTransfer call that don't works

2024-11-10 13:53 UTC, andygolay commented
So far:

- Eth -> Movement direction E2E test passes with `RUST_BACKTRACE=1 DOT_MOVEMENT_PATH="$(pwd)/.movement" cargo test --test bridge_e2e_test_framework test_bridge_transfer_eth_movement_happy_path -- --nocapture --test-threads=1`. Seems to be valid but could use another pair of eyes.

- I've added DO NOT MERGE to recent commits because:
  - in the Movement - Eth direction, I've modified `AtomicBridgeCounterpartyMOVE.sol` for debugging. Specifically:
    - `if (atomicBridgeInitiatorMOVE.poolBalance() < amount) revert InsufficientMOVEBalance();` is currently commented out in `lockBridgeTransfer.`
    - `atomicBridgeInitiatorMOVE.withdrawMOVE(details.recipient, details.amount);` is commented out in `completeBridgeTransfer`  
    - The above two lines MUST be uncommented and the Movement -> Eth direction test (`RUST_BACKTRACE=1 DOT_MOVEMENT_PATH="$(pwd)/.movement" cargo test --test bridge_e2e_test_framework test_bridge_transfer_movement_eth_happy_path -- --nocapture --test-threads=1`) MUST consistently pass before merging this PR.
  - I also modifying the Eth event monitoring for `counterpart_trlocked_event_filter` to have a timeout of 30 seconds for testing. It doesn't seem to help from what I can see.
- As of the latest commit, the relayer is flaky about receiving the Eth counterparty Locked event. Sometimes it does, sometimes it doesn't. I added logging in the test so in the testing terminal, the `LockDetails` are always outputted. So it seems that `lockBridgeTransfer` is successfully called on the Eth side, and the event is emitted. However the relayer isn't always picking it up.

2024-11-12 17:03 UTC, 0xPrimata requested changes

2024-11-12 17:03 UTC, 0xPrimata commented on protocol-units/bridge/contracts/src/AtomicBridgeCounterparty.sol
> +        console.log("verif done");
Please remove all console.log()s. They only serve for debugging and will weight on tx cost.

2024-11-19 11:09 UTC, 0xmovses commented
Some CI failing https://github.com/movementlabsxyz/movement/actions/runs/11911551471/job/33193286931?pr=690

2024-11-19 13:38 UTC, 0xmovses approved these changes

2024-11-19 13:41 UTC, merged