sketch
movementlabsxyz/movement pull request #772
Opened 2024-10-30 00:23 UTC by 0xPrimata

# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

# Changelog

# Testing

# Outstanding issues

2024-11-12 16:10 UTC, 0xmovses requested changes
We need the new abis moved into `abis/` directory also.

2024-11-12 16:26 UTC, 0xPrimata commented on protocol-units/bridge/contracts/script/AtomicBridgeMOVEDeployer.s.sol
> +                ownerAddress, // Owner of the contract
yes, so behavior won't change for now.

2024-11-12 16:48 UTC, 0xPrimata commented
@0xmovses added abis

2024-11-12 16:50 UTC, 0xmovses commented
Thanks, it seems that fixed client integration tests are imminently about to be merged to main, EOD / tomorrow morn. I would think its best for those fixed integration tests to go in then you get test these contract changes against main and we merge after that. 

Unless there is some other urgency I'm unaware of?

2024-11-12 16:56 UTC, 0xmovses commented
This is the PR fyi, https://github.com/movementlabsxyz/movement/pull/690/commits 

Some rather large changes required with the way we test against the framework. Old testing work had to be rewritten.

2024-11-20 14:18 UTC, 0xmovses commented
Putting this into draft as it refers to the old HTLC contracts, however we may want to refer to this code, so keeping it draft.

2024-11-22 19:32 UTC, andygolay approved these changes
LGTM, tests pass locally and logic seems to make sense.

2024-11-25 15:57 UTC, 0xmovses approved these changes
Looks good.

2025-03-31 15:44 UTC, closed without merging