ENG-508: Create a Load and Soak testing framework
movementlabsxyz/movement pull request #85
Opened 2024-05-29 13:13 UTC by musitdev

# Summary
- **Status**: `draft` 
- **RFCs**: 
- **Categories**:  Utils Test

Develop mini framework for load and soak testing

Initial architecture definition:

```mermaid
flowchart TD
  subgraph Execute process
    PROCESS("process-compose:
     Entry point, 
     start all process")
  end
  subgraph Full Node
    SUZ(Suzuka Node)
    CEL(celestia)
    SEQ(Sequencer)
  end
  subgraph Tester
    SCH("Scheduler:
    - Schedule client execution.
    - Use rayon to schedule 
    - Each client in its own thread.
    - When a client execution end, restart the client.
    - Store client execution info. Use formated logs" )
    CONF("Config:
    Define the test parameters")
    CLI("Client:
    - Execute one scenario one time.
    - Log: scenario errors.
     ")
    SCE("Scenario:
    Define the scenario steps.")
  end

  PROCESS-- Start -->SUZ
  PROCESS-- Start -->CEL
  PROCESS-- Start -->SEQ
  PROCESS-- Start -->SCH
  CONF-- Define Exec -->SCH
  SCH-- Start Execution -->CLI
  CLI-- Run the scenario -->SCE
  SCE-- Return exec result -->CLI
  CLI-- Return exec result -->SCH
```
Scenario are developed in Rust and are linked with the Test framework exe (submodule of the crate).

Execution data are written in a formatted log file to be processed later if needed

After the execution, the Test framework exe print on the stdout a final report.

I put the framework crate in `util/load-soak-testing`, see the changed files.

# Changelog

# Testing

# Outstanding issues

2024-06-03 09:02 UTC, musitdev commented
I don't know why I get a lot of previous commit. I've started from main and rebase it. If you've an idea.
The developed files are in util/load_soak_testing

2024-06-04 16:53 UTC, l-monninger commented
Overall this is good for now. But, please fix the typos and for organization, I would prefer to see the tests in the respective network or client crate instead of within the framework crate. I would prefer to include the framework where need and have the tests organized by service.

2024-06-05 12:49 UTC, musitdev commented
I move the crate in networks/suzuka/load-soak-testting
I've implemented a simple soak test that loop and execute scenario during the test duration.
I've corrected some typos mistake.
The remaining part is to run new scenarios from time to time in a cycling way on top of the base looping ones.

2024-06-06 09:38 UTC, l-monninger approved these changes

2024-06-06 09:38 UTC, l-monninger commented on networks/suzuka/load-soak-testing/src/lib.rs
> +	pub fn calcualte_average_exec_time_milli(sceanarios: &[ScenarioExecMetric]) -> u128 {
There are still typos in here.

2024-06-06 09:38 UTC, l-monninger commented on networks/suzuka/load-soak-testing/bin/basicalicebob.rs
> +	coin_client::CoinClient,
For organization, I still want you to move these out into the appropriate network crates. `suzuka-client` for example.

2024-06-06 09:39 UTC, l-monninger requested changes

2024-06-06 09:39 UTC, l-monninger commented on networks/suzuka/load-soak-testing/bin/demoscenario.rs
> +use anyhow::Result;
Please fix typos and change organization before merging.

2024-06-11 10:52 UTC, musitdev commented
Recreate the PR in #111 to remove unknown modifications.

2024-06-11 10:52 UTC, closed without merging