feat: auto-remove .movement if exists in justfile
movementlabsxyz/movement pull request #920
Opened 2024-12-04 14:50 UTC by 0xmovses

# Summary
Several times I run the just command to start the node or run tests and realise I have forgotten to remove `.movement`, this updates the justfile so that it will always remove that if it exists.

# Changelog
- Updates the justfile to include a function, runs that on every just command

# Testing
Ran 
```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui"
```
It worked as expected, it removed my already existing `.movement/` dir.

2024-12-04 14:59 UTC, andygolay commented on justfile
> +
Would it make sense to also remove `.data` if it's present, or is that not so consequential?

2024-12-04 15:03 UTC, andygolay approved these changes
Yep worked for me. Added one passing comment about `.data`, not sure why that dir keeps hanging around for me or if it matters.

2024-12-04 15:15 UTC, 0xmovses commented
Yeah .. let's leave .data/ out of the equation for now, we can deal with it later if continues to cause issues.

2024-12-04 15:25 UTC, andygolay requested changes
I'm getting this now on `movement-full-node`

<img width="561" alt="image" src="https://github.com/user-attachments/assets/d25e52e3-1aae-4a6c-b987-879b3fd5e294">

Tried a couple times and got that when running the local node

2024-12-04 15:35 UTC, 0xmovses commented
Strangely I do not, here is my output. Perhaps it is the dangling `.data/`. 

<img width="1510" alt="Screenshot 2024-12-04 at 15 34 51" src="https://github.com/user-attachments/assets/9b814c65-f64d-4947-9749-622b5672a1a7">

2024-12-04 15:38 UTC, Primata commented
@0xmovses do you nix develop before running the command?

2024-12-04 15:41 UTC, 0xmovses commented
No, but I always run the tests within the nix shell by running this single command, or variations of it.
```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui"
```

2024-12-09 13:26 UTC, l-monninger commented
@0xmovses I don't want this to be enforced as I often have to test restarting over state. Such tests are also part of the CI. See the committed changes.

2024-12-12 19:54 UTC, 0xmovses commented
Yeah was discussing this yesterday with others too. Let's leave in the manual step.

2024-12-12 19:54 UTC, closed without merging