Bridge: Restart the indexer
movementlabsxyz/movement pull request #942
Opened 2024-12-10 19:21 UTC by musitdev

# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.
Restart the indexer implementing this discussion #884 features.

# Changelog

* update indexer db and event processing
* Change health check monitoring loop to be use with the indexer
* update process compose overlay.
# Testing

To start only the bridge (Relayer Mode):
`CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge --keep-tui"`

To the Relayer and the indexer independently: 
`CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui"`
# Outstanding issues

The Indexer-Relayer Mode is not implemented. TODO

2024-12-10 23:14 UTC, andygolay approved these changes
LGTM, tests pass for me locally and code looks good.

2024-12-11 18:58 UTC, 0xmovses requested changes

2024-12-11 18:58 UTC, 0xmovses commented on protocol-units/bridge/service/tests/relayer.rs
> +fn calculated_transfer_bridfe_id(
```suggestion
fn calculate_bridge_transfer_id(
```

2024-12-11 18:58 UTC, 0xmovses commented on protocol-units/bridge/service/tests/relayer.rs
> +fn calculated_transfer_bridfe_id(
Update any calls to this function also.

2024-12-11 18:58 UTC, 0xmovses commented on protocol-units/bridge/service/tests/relayer.rs
> +			calculated_transfer_bridfe_id(&initiator.0, &recipient.0 .0, amount, nonce);
```suggestion
			calculate_bridge_transfer_id(&initiator.0, &recipient.0 .0, amount, nonce);
```

2024-12-11 18:58 UTC, 0xmovses commented on protocol-units/bridge/service/tests/relayer.rs
> +		calculated_transfer_bridfe_id(&initiator.0, &recipient.0, amount, nonce);
```suggestion
		calculate_bridge_transfer_id(&initiator.0, &recipient.0, amount, nonce);
```

2024-12-12 00:09 UTC, merged